// <auto-generated />
namespace SmartTeleHealth.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deploy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deploy));
        
        string IMigrationMetadata.Id
        {
            get { return "202102120136264_deploy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
